import asyncio
import datetime
import logging
from typing import Any, Dict, List, Optional
from langchain_experimental.agents.agent_toolkits import create_pandas_dataframe_agent
import pandas as pd
from app.agent.llm_parser import get_llm_client
from app.database.google_sheets import google_sheets_db
from app.database.mock_db import mock_db

logger = logging.getLogger("expense_agent.qa_agent")

QA_SYSTEM_PREFIX = """You are an intelligent financial analyst assistant for personal expenses.
You have access to a pandas dataframe 'df' containing the user's recorded expenses with columns:
- 'Date': Date of transaction (YYYY-MM-DD)
- 'Amount': Numerical monetary amount spent
- 'Currency': Currency label (e.g., Toman, Rial, USD)
- 'Category': Expense category (e.g., Food & Dining, Groceries, Shopping, Transportation, etc.)
- 'Description': Description/details of the purchase
- 'Bank': Source bank or payment method

Current Date: {current_date}

Instructions:
1. Carefully analyze the dataframe to answer the user's questions accurately.
2. Calculate sums, averages, comparisons, top categories, or monthly totals by executing Python/pandas code.
3. If the user asks in Persian (Farsi), reply in Persian. If they ask in English, reply in English.
4. Format monetary numbers cleanly with commas (e.g., 2,500,000 Toman).
5. Always provide a clear, concise, and helpful final answer.
"""


def _prepare_dataframe(raw_records: List[Dict[str, Any]]) -> pd.DataFrame:
    """Convert raw expense records into a normalized pandas DataFrame."""
    if not raw_records:
        return pd.DataFrame(columns=["Date", "Amount", "Currency", "Category", "Description", "Bank"])

    # 1. Normalize dictionary keys to avoid duplicate columns (e.g. 'amount' vs 'Amount')
    normalized_records = []
    for item in raw_records:
        row = {}
        for k, v in item.items():
            key_lower = str(k).strip().lower()
            if key_lower == "date":
                row["Date"] = str(v)
            elif key_lower == "amount":
                try:
                    row["Amount"] = float(v)
                except (ValueError, TypeError):
                    row["Amount"] = 0.0
            elif key_lower == "currency":
                row["Currency"] = str(v)
            elif key_lower == "category":
                row["Category"] = str(v)
            elif key_lower == "description":
                row["Description"] = str(v)
            elif key_lower == "bank":
                row["Bank"] = str(v)
            else:
                row[k] = v
        normalized_records.append(row)

    df = pd.DataFrame(normalized_records)

    # 2. Ensure required columns exist
    for col in ["Date", "Amount", "Currency", "Category", "Description", "Bank"]:
        if col not in df.columns:
            df[col] = "" if col != "Amount" else 0.0

    # 3. Clean types
    df["Amount"] = pd.to_numeric(df["Amount"], errors="coerce").fillna(0.0)
    df["Currency"] = df["Currency"].replace("", "Toman").fillna("Toman")
    df["Date"] = df["Date"].astype(str)
    df["Category"] = df["Category"].astype(str)
    df["Description"] = df["Description"].astype(str)
    df["Bank"] = df["Bank"].astype(str)

    return df[["Date", "Amount", "Currency", "Category", "Description", "Bank"]]


async def fetch_expenses_dataframe() -> pd.DataFrame:
    """Load expense records from Google Sheets (or fallback to local DB) into a DataFrame."""
    records = []
    if google_sheets_db.is_configured():
        try:
            records = await google_sheets_db.get_all_expenses()
            logger.info("Loaded %d records from Google Sheets for QA agent.", len(records))
        except Exception as e:
            logger.warning("Failed to fetch from Google Sheets: %s. Using local DB fallback.", e)
            records = await mock_db.get_all_expenses()
    else:
        records = await mock_db.get_all_expenses()
        logger.info("Loaded %d records from local JSON database for QA agent.", len(records))

    return _prepare_dataframe(records)


async def ask_expenses_agent(user_query: str) -> str:
    """Ask a natural language question about expenses using LangChain Pandas DataFrame Agent.

    Args:
        user_query: The natural language question (e.g. 'How much did I spend on food this month?').

    Returns:
        str: Detailed answer generated by the agent.
    """
    if not user_query or not user_query.strip():
        return "❓ Please provide a question after the `/ask` command (e.g., `/ask چقدر این ماه خرج غذا کردم؟`)."

    logger.info("[QA AGENT] Received user query: '%s'", user_query)
    df = await fetch_expenses_dataframe()

    if df.empty or len(df) == 0:
        return "📂 No expenses found in the database yet. Record some transactions first to start analyzing!"

    current_date = datetime.date.today().isoformat()
    prefix = QA_SYSTEM_PREFIX.format(current_date=current_date)

    def _run_agent_sync() -> str:
        llm = get_llm_client()
        agent = create_pandas_dataframe_agent(
            llm=llm,
            df=df,
            verbose=False,
            allow_dangerous_code=True,
            handle_parsing_errors=True,
            prefix=prefix,
            max_iterations=5,
            agent_type="openai-tools",
        )

        try:
            response = agent.invoke({"input": user_query})
            output = response.get("output", "")
            return output if output else "I couldn't calculate an answer for that query."
        except Exception as e:
            logger.error("Pandas agent execution failed: %s", e, exc_info=True)
            # Fallback to direct calculation heuristic or helpful error
            return f"⚠️ An error occurred while analyzing your data: {str(e)}"

    result_text = await asyncio.to_thread(_run_agent_sync)
    logger.info("[QA AGENT] Completed response: %s", result_text)
    return result_text
